{:user {:dependencies [[org.clojure/tools.namespace "0.2.11"]
                       [org.clojure/tools.trace "0.7.9"]]
        :plugins [[cider/cider-nrepl "0.17.0"]
                  [jonase/eastwood "0.2.6"]
                  [lein-ancient "0.6.15"]
                  [lein-cljfmt "0.5.7"]
                  [lein-exec "0.3.7"]
                  [lein-kibit "0.1.6"]
                  [lein-ring "0.12.4"]
                  [lein-pprint "1.2.0"]]}}
