{:user {:dependencies [[org.clojure/tools.namespace "0.2.11"]
                       [org.clojure/tools.trace "0.7.9"]]
        :plugins [[cider/cider-nrepl "0.17.0"]
                  [jonase/eastwood "0.2.5" :exclusions [org.clojure/clojure]]
                  [lein-ancient "0.6.14"]
                  [lein-cljfmt "0.5.7" :exclusions [org.clojure/clojure]]
                  [lein-exec "0.3.6"]
                  [lein-kibit "0.1.6" :exclusions [org.clojure/clojure]]
                  [lein-ring "0.12.1"]
                  [lein-pprint "1.1.2"]]}}
